#!/bin/bash

ssh-keygen -t ed25519 -C leotheasianlion@gmail.com

eval "$(ssh-agent -s)"

printf "Host *\n AddKeysToAgent yes\n IdentityFile ~/.ssh/id_ed25519" > ~/.ssh/config

ssh-add ~/.ssh/id_ed25519

cat ~/.ssh/id_ed25519.pub
#copy contents to github ssh key

ssh -T git@github.com

