#!/bin/bash

# set some colors
CNT="[\e[1;36mNOTE\e[0m]"
COK="[\e[1;32mOK\e[0m]"
CER="[\e[1;31mERROR\e[0m]"
CAT="[\e[1;37mATTENTION\e[0m]"
CWR="[\e[1;35mWARNING\e[0m]"
CAC="[\e[1;33mACTION\e[0m]"
INSTLOG="install.log"

#clear the screen
clear

# python poetry package manager
curl -sSL https://install.python-poetry.org | python3 -

# pyenv
#curl https://pyenv.run | bash

# add pyenv to fish config
#set -Ux PYENV_ROOT $HOME/.pyenv
#fish_add_path $PYENV_ROOT/bin

# install a certain python version
# pyenv install 3.12.10

sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update && sudo apt upgrade
sudo apt install fish -y

sudo locale-gen en_US.UTF-8
sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

# rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# terminal copy to clipboard tool
sudo apt install xclip -y

# mpv video player
# use '{' '}' keys to decrease or increase the playback speed of videos
#sudo apt install mpv -y

# fm6000
curl https://codeberg.org/anhsirk0/fetch-master-6000/raw/branch/main/fm6000.pl --output fm6000
chmod +x fm6000
mkdir -p ~/.local/bin/
cp fm6000 ~/.local/bin/

# setup symlink to config files
ln -s ~/projects/Configs/windows_11/dotfiles/fish/ ~/.config/
ln -s ~/projects/Configs/windows_11/dotfiles/nvim/ ~/.config/
ln -s ~/projects/Configs/windows_11/dotfiles/ranger/ ~/.config/
ln -s ~/projects/Configs/windows_11/dotfiles/tmux/ ~/.config/
ln -s ~/projects/Configs/windows_11/dotfiles/bashrc_extras.sh ~/

# use ls -l ~/.config/ to check symlinks
echo "source ~/bashrc_extras.sh" >>~/.bashrc

# sync windows directories to root folder
ln -s /mnt/c/Users/$USER/Downloads ~/downloads
ln -s /mnt/c/Users/$USER/Desktop ~/desktop
ln -s /mnt/c/Users/$USER/Pictures ~/pictures
ln -s /mnt/c/Users/$USER/Videos ~/videos

# more tools
sudo apt install -y ncdu cmake htop rpi-imager cheese tree neofetch cmatrix fish xsel fzf \ # fuzzy search
sqlite3 \
  zoxide \ # Remembers directories you visit often
ripgrep \ # insanely fast searching
bat \ # better cat
eza \ # modern replacement for ls
lazygit \ # pairs beautifully with LazyVim.
btop \ # modern htop replacement
direnv \ # automatically loads env vars per project.
delta \ # makes diffs gorgeous
dust \ # better du
procs \ # cleaner process listing

# yt-dlp (download youtube urls to local machine)
sudo add-apt-repository -y ppa:tomtomtom/yt-dlp # Add ppa repo to apt
sudo apt update                                 # Update package list
sudo apt install yt-dlp

# cleaner find
cargo install fd-find

# 7zip
sudo apt install p7zip-full

# fancy version of ls command
cargo install eza

# rust based terminal file manager
#cargo install --force yazi-build

# starship
curl -sS https://starship.rs/install.sh | sh

# oh-my-fish
# additional tools set up not in the arch repo:
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
omf install bang-bang
omf install https://github.com/Alaz-Oz/fish-insulter

# neovim version manager
cargo install --git https://github.com/MordechaiHadad/bob.git

# neovim build from source
# build prereqs
sudo apt-get install ninja-build gettext cmake unzip curl build-essential -y

# build neovim from source
git clone https://github.com/neovim/neovim /tmp/neovim/
cd /tmp/neovim/
make CMAKE_BUILD_TYPE=RelWithDebInfo
git checkout stable
sudo make install

# mise
curl https://mise.run | sh

# get latest dotnet sdk and runtime
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh
rm -f ./dotnet-install.sh

# tmux plugins (hit prefix key + shift + i to install plugins)
git clone https://github.com/tmux-plugins/tpm ~/projects/Configs/windows_11/dotfiles/tmux/plugins/tpm/

# register config with tmux
# tmux source-file ~/.config/tmux/tmux.conf

echo -e "type this in terminal if tmux is already running
tmux source ~/.config/tmux/tmux.conf"

echo -e "To swap caps lock and esc, install gnome tweaks from pop shop, go to keyboard & mouse and find it in additional options"

# nodejs and python
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&
  sudo apt install -y nodejs python3-pip

# to copy terminal command output to clipboard on xorg:
# echo "[your_linux_command]" | xsel -b

# bleeding edge trash-cli useful for tools such as lf
#sudo pip install git+https://github.com/andreafrancia/trash-cli

# faster neofetch
git clone https://github.com/fastfetch-cli/fastfetch.git && cd fastfetch
cmake -B build
cmake --build build
sudo cmake --install build

### Script is done ###
echo -e "$CNT - Script had completed!"

# run this in powershell as admin
# For showing toast notifications in windows:
# RemoteSigned = allows local scripts + trusted modules
# Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
#
#
# Install-Module BurntToast -Scope CurrentUser -Force
#
# this should work now:
# powershell.exe -Command "Import-Module BurntToast; New-BurntToastNotification -Text 'WSL', 'Hello from Linux'"
