#!/bin/bash

# python virtual environments configurations
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash miniconda.sh -bup ~/miniconda3
rm -f miniconda.sh

# if using fish shell, set path like so:
#set -gx PATH /path/to/custom/directory/miniconda3/bin $PATH
set -gx PATH ~/miniconda3/bin $PATH

conda create --name web_auto python=3.10
conda activate web_auto
pip install python-dotenv pygithub
#pip install -r /home/leo_zhang/Documents/GitHub/my_linux_configs/python_configs/envs/web_auto/web_auto.txt
conda deactivate

# make sure we dont open up in the base environment everytime we open up a new terminal
conda config --set auto_activate_base false
