#!/bin/bash

# for installing pyright
yay -S --needed --noconfirm npm

git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
rm -rf ~/.config/nvim/.gitignore

printf "add to options.lua: 
        local opt = vim.opt
        opt.wrap = true\n"
echo -e "set checker to false in lazy.lua"
echo -e "toggle clangd, cmake, docker, json, markdown, python, omnisharp, and prettier within :LazyExtras command"
