#!/bin/bash

# set up git ssh
# generate ssh key:
ssh-keygen -t ed25519 -C leotheasianlion@gmail.com
# to check ssh agent:
eval "$(ssh-agent -s)"
printf "Host *\n AddKeysToAgent yes\n IdentityFile ~/.ssh/id_ed25519" >~/.ssh/config
ssh-add ~/.ssh/id_ed25519
#add contents of "cat ~/.ssh/id_ed25519.pub" to github ssh key
run "ssh -T git@github.com"

# docker and docker-compose set up
sudo apt-get update && sudo apt-get upgrade -y
curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh
# To add the permissions to the current user run:
sudo usermod -aG docker ${USER}
#Check it running:
#groups ${USER}
# reboot then run the commands below
sudo apt-get install libffi-dev libssl-dev python3 python3-pip python3-dev docker-compose -y
sudo systemctl enable docker && docker run hello-world

# projects setup
mkdir ~/projects
cd ~/projects
git clone git@github.com:centuryhopper/Tools.git && git clone git@github.com:centuryhopper/Bots.git

# case insensitive tab completion
echo "bind -s 'set completion-ignore-case on'" >>~/.bashrc

# nginx

# dotnet 8
wget -O - https://raw.githubusercontent.com/pjgpetecodes/dotnet8pi/main/install.sh | sudo bash
# sudo reboot
