
#map dT shell mv %s /home/${USER}/.local/share/Trash/files/
map dT shell trash-put %s
map gh cd ~/Documents/GitHub/
map gd cd ~/Downloads/
map gH cd ~/
map gc cd ~/.config/


set draw_borders both


map r rename
map y yank
map x cut
map p paste


