[mgr]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 5

[opener]
edit = [
    { run = "nvim %s", block = true, desc = "Neovim", for = "unix" },
]
