#!/bin/bash

#start swwww
swww query || swww init

#figure out which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

# Get the randomly selected filename
wallpaper=$(find ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/Wallpapers/.config/Wallpapers/ -type f | shuf -n 1)

echo $wallpaper

#show the correct wallpapper based on the theme
if [ $THEMEIS == "dark.css" ]; then
    swww img $wallpaper --resize fit
else
    swww img ~/.config/hypr/Wallpapers/Wallpapers/wallpaper.jpg --resize fit
fi
