#!/bin/bash


# store in public repo
cp -r ~/.config/fish/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/fish/.config/fish/

cp -r ~/.config/hypr/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/hypr/.config/hypr/

cp -r ~/.config/lf/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/lf/.config/lf/

cp -r ~/.config/kitty/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/kitty/.config/kitty/

cp -r ~/.config/mako/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/mako/.config/mako/


#cp -r ~/.config/nvim ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/nvim/.config/nvim/

cp -r ~/.config/shaders/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/shaders/.config/shaders/

cp -r ~/.config/waybar/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/waybar/.config/waybar/

cp -r ~/.config/wlogout/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/wlogout/.config/wlogout/

cp -r ~/.config/wofi/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/wofi/.config/wofi/

cp -r ~/.config/Wallpapers/* ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/Wallpapers/

# bashrc
cp ~/.bashrc ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/.bashrc

# starship
cp ~/.config/starship.toml ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/extras/starship.toml








