#!/bin/bash

cd ~/Documents/GitHub
git clone git@github.com:centuryhopper/Bots.git
#git clone git@github.com:centuryhopper/Configs.git
git clone git@github.com:centuryhopper/important_docs.git
git clone git@github.com:centuryhopper/Journal.git
git clone git@github.com:centuryhopper/MachineLearning_Practice.git
git clone git@github.com:centuryhopper/PasswordManagerDotNet.git
git clone git@github.com:centuryhopper/practice_interview_problems.git
git clone git@github.com:centuryhopper/Tools.git
