#!/bin/bash

cd ~/Documents/GitHub
git clone git@github.com:leozhang1/Bots.git
#git clone git@github.com:leozhang1/Configs.git
git clone git@github.com:leozhang1/important_docs.git
git clone git@github.com:leozhang1/Journal.git
git clone git@github.com:leozhang1/MachineLearning_Practice.git
git clone git@github.com:leozhang1/PasswordManager_DotNet.git
git clone git@github.com:leozhang1/practice_interview_problems.git
git clone git@github.com:leozhang1/Tools.git
