#!/bin/bash

ssh-keygen -t ed25519 -C leotheasianlion@gmail.com
eval "ssh-agent -s" > ~/.ssh/tmp.txt

# export variables using fish syntax
# for example: if the contents of tmp.txt are:
#   SSH_AUTH_SOCK=/tmp/ssh-XXXXXXpXE7bl/agent.21856; export SSH_AUTH_SOCK;
#   SSH_AGENT_PID=21858; export SSH_AGENT_PID;
#   echo Agent pid 21858;
# then the commands run are set -x SSH_AUTH_SOCK /tmp/ssh-XXXXXXpXE7bl/agent.21856
# and set -x SSH_AGENT_PID 21858 

# Read the file and extract the values using grep and regular expressions
file_contents=$(cat ~/.ssh/tmp.txt)

# Extracting auth sock
ssh_auth_sock=$(echo "$file_contents" | grep -oP '(?<=SSH_AUTH_SOCK=).*?(?=;)')

# Extracting pid
ssh_agent_pid=$(echo "$file_contents" | grep -oP '(?<=SSH_AGENT_PID=).*?(?=;)')

#echo "SSH_AUTH_SOCK: $ssh_auth_sock"
#echo "SSH_AGENT_PID: $ssh_agent_pid"

fish_path=$(which fish) # Get the path to the Fish interpreter

if [ -x "$fish_path" ]; then
    "$fish_path" ~/Documents/GitHub/Configs/arch_linux_hyprland/dotfiles/extras/scripts/set_variables.fish "$ssh_auth_sock" "$ssh_agent_pid"
else
    echo "Fish interpreter not found."
fi

printf "Host *\n AddKeysToAgent yes\n IdentityFile ~/.ssh/id_ed25519" > ~/.ssh/config

ssh-add ~/.ssh/id_ed25519

wl-copy < ~/.ssh/id_ed25519.pub
echo -e "TODO: add contents of 'cat ~/.ssh/id_ed25519.pub' to github ssh key"
echo -e "TODO: then run: ssh -T git@github.com"


