#!/bin/bash

git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
rm -rf ~/.config/nvim/.gitignore

printf "add to options.lua: 
        local opt = vim.opt
        opt.wrap = true\n"
echo -e "toggle rust, python, omnisharp, and vscode on within :LazyExtras command"
