#!/bin/bash

# store in public repo
cp -r ~/.config/fish/* ~/Documents/GitHub/Configs/Pop_OS/dotfiles/fish/

# should pull from github for most up to date version
cp -r ~/.config/nvim/* ~/Documents/GitHub/Configs/Pop_OS/dotfiles/nvim/

cp -r ~/.config/tmux/* ~/Documents/GitHub/Configs/Pop_OS/dotfiles/tmux/

# bashrc
cp ~/.bashrc ~/Documents/GitHub/Configs/Pop_OS/dotfiles/.bashrc

# ranger
cp ~/.config/ranger/* ~/Documents/GitHub/Configs/Pop_OS/dotfiles/ranger/

# starship
#cp ~/.config/starship.toml ~/Documents/GitHub/Configs/Pop_OS/dotfiles/extras/starship.toml
